export const defaultBoardImages = [
  {
    id: "Hd7vwFzZpH0",
    title_name: "Tasks",
    slug: "cat-licking-its-paw-Hd7vwFzZpH0",
    alternative_slugs: {
      en: "cat-licking-its-paw-Hd7vwFzZpH0",
      es: "gato-lamiendose-la-pata-Hd7vwFzZpH0",
      ja: "猫は足を舐めている-Hd7vwFzZpH0",
      fr: "chat-se-lechant-la-patte-Hd7vwFzZpH0",
      it: "gatto-che-si-lecca-la-zampa-Hd7vwFzZpH0",
      ko: "앞발을-핥는-고양이-Hd7vwFzZpH0",
      de: "katze-leckt-sich-die-pfote-Hd7vwFzZpH0",
      pt: "gato-lambendo-a-pata-Hd7vwFzZpH0",
    },
    created_at: "2017-11-21T14:49:18Z",
    updated_at: "2024-03-15T16:40:16Z",
    promoted_at: "2017-11-21T15:48:52Z",
    width: 6321,
    height: 4214,
    color: "#737373",
    blur_hash: "LBC6_o^,4mRi?ckBRPs;4,ITnk%M",
    description: null,
    alt_description: "cat licking its paw",
    breadcrumbs: [
      {
        slug: "images",
        title: "1,000,000+ Free Images",
        index: 0,
        type: "landing_page",
      },
      {
        slug: "feelings",
        title: "Feelings Images",
        index: 1,
        type: "landing_page",
      },
      {
        slug: "cute",
        title: "Cute Images & Pictures",
        index: 2,
        type: "landing_page",
      },
    ],
    urls: {
      raw: "https://images.unsplash.com/photo-1511275539165-cc46b1ee89bf?ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjY5MjN8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1511275539165-cc46b1ee89bf?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjY5MjN8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1511275539165-cc46b1ee89bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjY5MjN8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1511275539165-cc46b1ee89bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjY5MjN8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1511275539165-cc46b1ee89bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjY5MjN8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1511275539165-cc46b1ee89bf",
    },
    links: {
      self: "https://api.unsplash.com/photos/cat-licking-its-paw-Hd7vwFzZpH0",
      html: "https://unsplash.com/photos/cat-licking-its-paw-Hd7vwFzZpH0",
      download:
        "https://unsplash.com/photos/Hd7vwFzZpH0/download?ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjY5MjN8",
      download_location:
        "https://api.unsplash.com/photos/Hd7vwFzZpH0/download?ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjY5MjN8",
    },
    likes: 1347,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      animals: { status: "approved", approved_on: "2020-04-06T14:20:16Z" },
    },
    asset_type: "photo",
    user: {
      id: "4qFzXWWUZ20",
      updated_at: "2024-02-23T16:29:16Z",
      username: "madeyes",
      name: "Eric Han",
      first_name: "Eric",
      last_name: "Han",
      twitter_username: null,
      portfolio_url: null,
      bio: null,
      location: "ShiJiaZhuang. HeBei.  CN",
      links: {
        self: "https://api.unsplash.com/users/madeyes",
        html: "https://unsplash.com/@madeyes",
        photos: "https://api.unsplash.com/users/madeyes/photos",
        likes: "https://api.unsplash.com/users/madeyes/likes",
        portfolio: "https://api.unsplash.com/users/madeyes/portfolio",
        following: "https://api.unsplash.com/users/madeyes/following",
        followers: "https://api.unsplash.com/users/madeyes/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1510656492992-e4b34e16dbdd?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1510656492992-e4b34e16dbdd?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1510656492992-e4b34e16dbdd?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: null,
      total_collections: 3,
      total_likes: 2,
      total_photos: 16,
      total_promoted_photos: 4,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: null,
        portfolio_url: null,
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "Canon",
      model: "Canon EOS 5D Mark IV",
      name: "Canon, EOS 5D Mark IV",
      exposure_time: "1/125",
      aperture: "1.4",
      focal_length: "35.0",
      iso: 800,
    },
    location: {
      name: "Shijiazhuang, China",
      city: "Shijiazhuang",
      country: "China",
      position: { latitude: 38.042805, longitude: 114.514893 },
    },
    meta: { index: true },
    public_domain: false,
    tags: [
      { type: "landing_page", title: "cat", source: [Object] },
      { type: "landing_page", title: "grey", source: [Object] },
      { type: "landing_page", title: "animal", source: [Object] },
      { type: "search", title: "pet" },
      { type: "search", title: "china" },
      { type: "search", title: "shijiazhuang" },
      { type: "search", title: "feline" },
      { type: "landing_page", title: "kitten", source: [Object] },
      { type: "search", title: "portrait" },
      { type: "search", title: "tongue" },
    ],
    tags_preview: [
      { type: "landing_page", title: "cat", source: [Object] },
      { type: "landing_page", title: "grey", source: [Object] },
      { type: "landing_page", title: "animal", source: [Object] },
    ],
    views: 33263130,
    downloads: 168154,
    topics: [
      {
        id: "Jpg6Kidl-Hk",
        title: "Animals",
        slug: "animals",
        visibility: "featured",
      },
    ],
    related_collections: {
      total: 3,
      type: "related",
      results: [[Object], [Object], [Object]],
    },
  },
  {
    id: "4Qd2KkJCXOk",
    title_name: "Projects",
    slug: "red-rose-with-black-background-4Qd2KkJCXOk",
    alternative_slugs: {
      en: "red-rose-with-black-background-4Qd2KkJCXOk",
      es: "rosa-roja-con-fondo-negro-4Qd2KkJCXOk",
      ja: "黒い背景に赤いバラ-4Qd2KkJCXOk",
      fr: "rose-rouge-sur-fond-noir-4Qd2KkJCXOk",
      it: "rosa-rossa-con-sfondo-nero-4Qd2KkJCXOk",
      ko: "검은-배경의-빨간-장미-4Qd2KkJCXOk",
      de: "rote-rose-mit-schwarzem-hintergrund-4Qd2KkJCXOk",
      pt: "rosa-vermelha-com-fundo-preto-4Qd2KkJCXOk",
    },
    created_at: "2018-07-27T23:12:55Z",
    updated_at: "2024-03-16T11:47:42Z",
    promoted_at: "2018-07-28T12:30:09Z",
    width: 4912,
    height: 3264,
    color: "#260c26",
    blur_hash: "L55|ECa}2rfRsCa|Sfo1J,jtwda|",
    description:
      "I took this photo a while back and only recently ran it through post. I am very happy with the results.",
    alt_description: "red rose with black background",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1532732789821-e69c5633391e?ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcxNTl8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1532732789821-e69c5633391e?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcxNTl8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1532732789821-e69c5633391e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcxNTl8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1532732789821-e69c5633391e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcxNTl8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1532732789821-e69c5633391e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcxNTl8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1532732789821-e69c5633391e",
    },
    links: {
      self: "https://api.unsplash.com/photos/red-rose-with-black-background-4Qd2KkJCXOk",
      html: "https://unsplash.com/photos/red-rose-with-black-background-4Qd2KkJCXOk",
      download:
        "https://unsplash.com/photos/4Qd2KkJCXOk/download?ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcxNTl8",
      download_location:
        "https://api.unsplash.com/photos/4Qd2KkJCXOk/download?ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcxNTl8",
    },
    likes: 346,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {},
    asset_type: "photo",
    user: {
      id: "Yr1c70yLv84",
      updated_at: "2024-03-05T22:25:11Z",
      username: "timothycdykes",
      name: "Timothy Dykes",
      first_name: "Timothy",
      last_name: "Dykes",
      twitter_username: null,
      portfolio_url: "https://photo.timothycdykes.me/",
      bio: "Outdoor and technology enthusiast, passionate about photography. If you like my work, please consider supporting me by making a donation, visiting my website, and linking to my website in your photo credits!",
      location: null,
      links: {
        self: "https://api.unsplash.com/users/timothycdykes",
        html: "https://unsplash.com/@timothycdykes",
        photos: "https://api.unsplash.com/users/timothycdykes/photos",
        likes: "https://api.unsplash.com/users/timothycdykes/likes",
        portfolio: "https://api.unsplash.com/users/timothycdykes/portfolio",
        following: "https://api.unsplash.com/users/timothycdykes/following",
        followers: "https://api.unsplash.com/users/timothycdykes/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1676290929114-b87dc6693293image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1676290929114-b87dc6693293image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1676290929114-b87dc6693293image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "timothycdykes",
      total_collections: 13,
      total_likes: 799,
      total_photos: 612,
      total_promoted_photos: 87,
      accepted_tos: true,
      for_hire: false,
      social: {
        instagram_username: "timothycdykes",
        portfolio_url: "https://photo.timothycdykes.me/",
        twitter_username: null,
        paypal_email: null,
      },
    },
    exif: {
      make: "SONY",
      model: "SLT-A55V",
      name: "SONY, SLT-A55V",
      exposure_time: "1/2000",
      aperture: "1.8",
      focal_length: "50.0",
      iso: 1600,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: { latitude: null, longitude: null },
    },
    meta: { index: true },
    public_domain: false,
    tags: [
      { type: "landing_page", title: "flower", source: [Object] },
      { type: "search", title: "plant" },
      { type: "landing_page", title: "brown", source: [Object] },
      { type: "landing_page", title: "water", source: [Object] },
      { type: "search", title: "passion" },
      { type: "landing_page", title: "red", source: [Object] },
      { type: "search", title: "petal" },
      { type: "search", title: "dew" },
      { type: "search", title: "rain" },
      { type: "search", title: "valentine" },
      { type: "landing_page", title: "nature", source: [Object] },
      { type: "search", title: "garden" },
      { type: "search", title: "outdoors" },
      { type: "landing_page", title: "person", source: [Object] },
      { type: "search", title: "human" },
      { type: "landing_page", title: "people", source: [Object] },
      { type: "search", title: "geranium" },
      { type: "search", title: "blossom" },
      { type: "search", title: "flora" },
      { type: "search", title: "carnation" },
    ],
    tags_preview: [
      { type: "landing_page", title: "flower", source: [Object] },
      { type: "search", title: "plant" },
      { type: "landing_page", title: "brown", source: [Object] },
    ],
    views: 7412256,
    downloads: 18659,
    topics: [],
    related_collections: {
      total: 3,
      type: "related",
      results: [[Object], [Object], [Object]],
    },
  },
  {
    id: "4XXNWJJ4msg",
    title_name: "Users",
    slug: "blue-ocean-4XXNWJJ4msg",
    alternative_slugs: {
      en: "blue-ocean-4XXNWJJ4msg",
      es: "oceano-azul-4XXNWJJ4msg",
      ja: "ブルーオーシャン-4XXNWJJ4msg",
      fr: "ocean-bleu-4XXNWJJ4msg",
      it: "oceano-blu-4XXNWJJ4msg",
      ko: "블루-오션-4XXNWJJ4msg",
      de: "blauer-ozean-4XXNWJJ4msg",
      pt: "oceano-azul-4XXNWJJ4msg",
    },
    created_at: "2018-12-11T17:10:40Z",
    updated_at: "2024-03-16T10:48:52Z",
    promoted_at: "2018-12-12T11:26:27Z",
    width: 5464,
    height: 3640,
    color: "#262626",
    blur_hash: "LMFP4}4.=|xD_}S5$$xZMc%MjExF",
    description: null,
    alt_description: "blue ocean",
    breadcrumbs: [],
    urls: {
      raw: "https://images.unsplash.com/photo-1544548188-597e0d9e50bf?ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcyMzN8&ixlib=rb-4.0.3",
      full: "https://images.unsplash.com/photo-1544548188-597e0d9e50bf?crop=entropy&cs=srgb&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcyMzN8&ixlib=rb-4.0.3&q=85",
      regular:
        "https://images.unsplash.com/photo-1544548188-597e0d9e50bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcyMzN8&ixlib=rb-4.0.3&q=80&w=1080",
      small:
        "https://images.unsplash.com/photo-1544548188-597e0d9e50bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcyMzN8&ixlib=rb-4.0.3&q=80&w=400",
      thumb:
        "https://images.unsplash.com/photo-1544548188-597e0d9e50bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcyMzN8&ixlib=rb-4.0.3&q=80&w=200",
      small_s3:
        "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1544548188-597e0d9e50bf",
    },
    links: {
      self: "https://api.unsplash.com/photos/blue-ocean-4XXNWJJ4msg",
      html: "https://unsplash.com/photos/blue-ocean-4XXNWJJ4msg",
      download:
        "https://unsplash.com/photos/4XXNWJJ4msg/download?ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcyMzN8",
      download_location:
        "https://api.unsplash.com/photos/4XXNWJJ4msg/download?ixid=M3w1NjQ2Mjl8MHwxfGFsbHx8fHx8fHx8fDE3MTA2NjcyMzN8",
    },
    likes: 650,
    liked_by_user: false,
    current_user_collections: [],
    sponsorship: null,
    topic_submissions: {
      nature: { status: "approved", approved_on: "2020-04-06T14:20:12Z" },
    },
    asset_type: "photo",
    user: {
      id: "4zTK95lwDUg",
      updated_at: "2024-01-13T10:42:58Z",
      username: "lenroth",
      name: "Len Roth",
      first_name: "Len",
      last_name: "Roth",
      twitter_username: "lenrroth",
      portfolio_url: "https://www.instagram.com/lenroth/",
      bio: "adventure & lifestyle photographer / filmmaker\r\n\r\n\r\n",
      location: "Zürich, Schweiz",
      links: {
        self: "https://api.unsplash.com/users/lenroth",
        html: "https://unsplash.com/@lenroth",
        photos: "https://api.unsplash.com/users/lenroth/photos",
        likes: "https://api.unsplash.com/users/lenroth/likes",
        portfolio: "https://api.unsplash.com/users/lenroth/portfolio",
        following: "https://api.unsplash.com/users/lenroth/following",
        followers: "https://api.unsplash.com/users/lenroth/followers",
      },
      profile_image: {
        small:
          "https://images.unsplash.com/profile-1550072218351-6aa096f00d33?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
        medium:
          "https://images.unsplash.com/profile-1550072218351-6aa096f00d33?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
        large:
          "https://images.unsplash.com/profile-1550072218351-6aa096f00d33?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
      },
      instagram_username: "lenroth",
      total_collections: 1,
      total_likes: 20,
      total_photos: 2,
      total_promoted_photos: 2,
      accepted_tos: true,
      for_hire: true,
      social: {
        instagram_username: "lenroth",
        portfolio_url: "https://www.instagram.com/lenroth/",
        twitter_username: "lenrroth",
        paypal_email: null,
      },
    },
    exif: {
      make: "DJI",
      model: "Mavic 2 Pro",
      name: "DJI, Mavic 2 Pro",
      exposure_time: "1/640",
      aperture: "5.6",
      focal_length: "28",
      iso: 100,
    },
    location: {
      name: null,
      city: null,
      country: null,
      position: { latitude: null, longitude: null },
    },
    meta: { index: true },
    public_domain: false,
    tags: [
      { type: "landing_page", title: "nature", source: [Object] },
      { type: "search", title: "outdoors" },
      { type: "landing_page", title: "ocean", source: [Object] },
      { type: "search", title: "sea" },
      { type: "landing_page", title: "water", source: [Object] },
      { type: "landing_page", title: "mountain", source: [Object] },
      { type: "landing_page", title: "blue", source: [Object] },
      { type: "search", title: "ice" },
      { type: "landing_page", title: "scenery", source: [Object] },
      { type: "landing_page", title: "snow", source: [Object] },
      { type: "landing_page", title: "landscape", source: [Object] },
      { type: "search", title: "sea waves" },
      { type: "search", title: "reef" },
      { type: "search", title: "sea life" },
      { type: "landing_page", title: "animal", source: [Object] },
      { type: "search", title: "cliff" },
    ],
    tags_preview: [
      { type: "landing_page", title: "nature", source: [Object] },
      { type: "search", title: "outdoors" },
      { type: "landing_page", title: "ocean", source: [Object] },
    ],
    views: 7886362,
    downloads: 21471,
    topics: [
      {
        id: "6sMVjTLSkeQ",
        title: "Nature",
        slug: "nature",
        visibility: "featured",
      },
    ],
    related_collections: {
      total: 3,
      type: "related",
      results: [[Object], [Object], [Object]],
    },
  },
];
